packages:
  - "core"
  - "knex"
  - "pg"
  - "browser"
  - "graphql"
  - "benchmarks"
  - "compat"
  - "scripts"

catalog:
  "typescript": 5.9.3
  "pg": 8.18.0
  "@types/pg": 8.16.0
  "@electric-sql/pglite": 0.3.15
  "knex": 3.1.0
  "better-sqlite3": 12.6.2
  "sqlite3": 5.1.7
  "mysql": 2.18.1
  "mysql2": 3.17.2
  "tedious": 19.2.1
  "pg-query-stream": 4.12.0
  "oracledb": 6.10.0
  "crc": 4.3.2
  "crc-32": 1.2.2
  "luxon": 3.7.2
  "tinybench": 6.0.0
  "@tsconfig/node-lts": 24.0.0
  "@types/luxon": 3.7.1
  "@types/node": 25.2.3
  "@types/bun": 1.3.9
  "glob": 13.0.4
  "@vitest/browser": 4.0.18
  "playwright": 1.58.2
  "vitest": 4.0.18
  "date-fns": 4.1.0
  "events": 3.3.0
  "util": 0.12.5
  "@vitest/browser-playwright": 4.0.18
  "vite-plugin-node-polyfills": 0.25.0