packages:
  - "core"
  - "knex"
  - "pg"
  - "browser"
  - "graphql"
  - "benchmarks"
  - "compat"

catalog:
  "typescript": 5.9.3
  "crc": 4.3.2
  "crc-32": 1.2.2
  "knex": 3.1.0
  "luxon": 3.7.2
  "pg": 8.18.0
  "@types/pg": 8.16.0
  "tinybench": 6.0.0
  "@tsconfig/node-lts": 24.0.0
  "@types/luxon": 3.7.1
  "@types/node": 25.2.3
  "@types/bun": 1.3.9
  "glob": 13.0.4
  "@vitest/browser": 4.0.18
  "playwright": 1.58.2
  "vitest": 4.0.18
  "@electric-sql/pglite": 0.3.15
  "date-fns": 4.1.0
  "events": 3.3.0
  "util": 0.12.5
  "@vitest/browser-playwright": 4.0.18