name: Release Core Package

on:
  workflow_dispatch:
  # push:
  #   branches: ["main"]

jobs:
  release:
    name: Release Core Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest-9
          run_install: false

      - name: Install Dependencies
        run: pnpm install
        working-directory: core/

      - name: Build packages
        run: pnpm build
        working-directory: core/

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          package: core
          token: ${{ secrets.NPM_ACCESS_TOKEN }}