name: Publish All Packages

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  core:
    name: Publish Core Package
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest-9
          run_install: false

      - name: Build Package
        run: pnpm install && pnpm build
        working-directory: core/
      
      - name: Test Package
        run: pnpm test
        working-directory: core/

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          package: core
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          access: public
  knex:
    name: Publish Knex Package
    runs-on: ubuntu-24.04
    needs: core

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest-9
          run_install: false

      - name: Build Package
        run: pnpm install && pnpm build
        working-directory: knex/

      - name: Test Package
        run: pnpm test
        working-directory: knex/

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          package: knex
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          access: public
  graphql:
    name: Publish GraphQL Package
    runs-on: ubuntu-24.04
    needs: core

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest-9
          run_install: false

      - name: Build Package
        run: pnpm install && pnpm build
        working-directory: graphql/

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          package: graphql
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          access: public
  pg:
    name: Publish Pg Package
    runs-on: ubuntu-24.04
    needs: [core, knex]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest-9
          run_install: false

      - name: Build Package
        run: pnpm install && pnpm build
        working-directory: pg/

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          package: pg
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          access: public
  browser:
    name: Publish Browser Package
    runs-on: ubuntu-24.04
    needs: [core, knex]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest-9
          run_install: false

      - name: Build Package
        run: pnpm install && pnpm build
        working-directory: browser/

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          package: browser
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          access: public
  benchmark:
    name: Benchmark Packages
    runs-on: ubuntu-24.04
    needs: [core, knex, pg, browser]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest-9
          run_install: false

      - name: Build Package
        run: pnpm install && pnpm build
        working-directory: benchmarks/
      
      - name: Run Benchmarks
        run: pnpm run ci
        working-directory: benchmarks/
